### ISSUE TITLE
EECS 370 Honor Code Violation

### ISSUE THREAD

**Issue by Faryab** [mhacks/hacker-boards-refactor#1]
Hello,

I'm a staff member of the current EECS370 Staff. I see that you have published the 370 solutions online in a public repo. This could have been a mistake so I just wanted to ask you to make this a private repo or take the solutions down. Posting project solutions online is against the engineering honor code and course policy.

This repo contains solutions for EECS370 Projects (https://www.eecs.umich.edu/courses/eecs370/eecs370.f20/projects/)
Specifically the file:
https://github.com/mhacks/hacker-boards-refactor/blob/fd6d313f4ba2e8ff64c2325ebc6c6d717004ae1b/hardware/rev4/simulate..c

If action is not taken in the next couple of days we will be forced to file a DCMA claim on Github.

Thanks,
K. Faryab Haye - EECS 370 Staff
University of Michigan
https://www.eecs.umich.edu/courses/eecs370/eecs370.f20/

**Comment by szechy** [comment]
Hi Faryab,

I have two questions about this:

- First: EECS370 is still using the same projects and website as the W2016 class? How long have these projects been in use, and how long has the website been in use?
- Second: how would a DCMA claim work against IP created by a a student (namely, a program/solutions)?

We've went ahead and removed the offending file from all commits on this repo.

Thanks,

Colin

**Comment by Faryab** [comment]
Hey Colin,

Yes. The class is still using the same projects. The website is updated every semester but has basically been the same for a while AFAIK.

I'm not sure if a DCMA claim would work against IP Created by a student actually, I think it might be the [sensitive data removal policy](https://docs.github.com/en/github/site-policy/github-sensitive-data-removal-policy) that applies more to this situation. Thank you for pointing it out! 

In either case, I appreciate your responding to this quickly. The best way to prevent cheating is to be proactive about removing sources on the internet. 

Thank you,
K. Faryab Haye - EECS 370 Staff
University of Michigan
